# Generated by Django 5.1.3 on 2025-02-22 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Competition', 'Competition'), ('Workshop', 'Workshop'), ('Meetup', 'Meetup'), ('Event', 'Event')], max_length=50)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event_images/')),
                ('location', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('event_time', models.TimeField()),
                ('organizer', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('members', models.IntegerField(default=1)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('school', 'School')], default='individual', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('member_class', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='QRapp.eventapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name_ml', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name in Malayalam')),
                ('description_ml', models.TextField(blank=True, null=True, verbose_name='Description in Malayalam')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('image_ids', models.CharField(max_length=255)),
                ('qr_code_image', models.ImageField(upload_to='qr_codes/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibits/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('caption_ml', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='QRapp.exhibit')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
