# Generated by Django 5.1.3 on 2025-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='student_classes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='student_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='student_phones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('school', 'School'), ('other', 'Other')], default='individual', max_length=20),
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
