# Generated by Django 5.1.3 on 2025-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRapp', '0002_eventapplication_student_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='description_ml',
            field=models.TextField(default='', verbose_name='Description in Malayalam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name_ml',
            field=models.CharField(default='', max_length=255, verbose_name='Name in Malayalam'),
            preserve_default=False,
        ),
    ]
