# Generated by Django 5.1.3 on 2025-03-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRapp', '0003_alter_exhibit_description_ml_alter_exhibit_name_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('school', 'School'), ('high school', 'high school'), ('academy', 'academy')], default='individual', max_length=20),
        ),
    ]
